SteinbauerIT:
  Flow:
    Essentials:
      login:
        ifAuthenticated:
          class: Acme\Package\Domain\Service\IsAuthenticated
          redirectToUri: /dashboard
        afterLogout:
          class: Acme\Package\Domain\Service\Logout
          redirectToUri: /homepage
        onAuthenticationSuccess:
          class: Acme\Package\Domain\Service\AuthSuccess
          redirectToUri: /dashboard
        onAuthenticationFailure:
          class: Acme\Package\Domain\Service\AuthFailure
          redirectToUri: /homepage
      account:
        authenticationProviderName: SteinbauerIT.Flow.Essentials:Login
        defaultRole: SteinbauerIT.Flow.Essentials:User
        afterCreateAccount:
          class: Acme\Package\Domain\Service\UserService
      mail:
        senderMail: noreply@steinbauer-it.com
        senderName: Steinbauer IT
