Neos:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: 'flowreact'
        user: 'root'
        password: 'dockyard'
        host: 'dockyard_db'
  Imagine:
    driver: 'Imagick'
    enabledDrivers:
      Vips: true
      Gd: true
      Imagick: true